# Generated by Django 5.0.2 on 2024-02-16 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('link', models.URLField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryDE',
            fields=[
            ],
            options={
                'verbose_name': 'DE Category',
                'verbose_name_plural': 'DE Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('amazonSeller.category',),
        ),
        migrations.CreateModel(
            name='CategoryUS',
            fields=[
            ],
            options={
                'verbose_name': 'US Category',
                'verbose_name_plural': 'US Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('amazonSeller.category',),
        ),
        migrations.AddField(
            model_name='category',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazonSeller.country'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('link', models.URLField(max_length=255, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='amazonSeller.category')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazonSeller.country')),
            ],
        ),
        migrations.CreateModel(
            name='De_productInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=500, null=True)),
                ('store_name', models.CharField(max_length=255, null=True)),
                ('seller_name', models.CharField(max_length=255, null=True)),
                ('seller_id', models.CharField(max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('about_seller', models.TextField(null=True)),
                ('seller_detailed_info', models.TextField(null=True)),
                ('scraped', models.BooleanField(default=False)),
                ('contacted', models.BooleanField(default=False)),
                ('main_category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='amazonSeller.category')),
                ('sub_category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='amazonSeller.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Us_productInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=500, null=True)),
                ('store_name', models.CharField(max_length=255, null=True)),
                ('seller_name', models.CharField(max_length=255, null=True)),
                ('seller_id', models.CharField(max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('about_seller', models.TextField(null=True)),
                ('seller_detailed_info', models.TextField(null=True)),
                ('scraped', models.BooleanField(default=False)),
                ('contacted', models.BooleanField(default=False)),
                ('main_category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='amazonSeller.category')),
                ('sub_category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='amazonSeller.subcategory')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'country')},
        ),
    ]
