# Generated by Django 5.0.2 on 2024-02-10 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('link', models.URLField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='amazonSeller.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=255, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('store_name', models.CharField(max_length=255)),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_id', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('about_seller', models.TextField()),
                ('seller_detailed_info', models.TextField()),
                ('scraped', models.BooleanField(default=False)),
                ('contacted', models.BooleanField(default=False)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_category_products', to='amazonSeller.category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_products', to='amazonSeller.subcategory')),
            ],
        ),
    ]
