# Generated by Django 5.0 on 2023-12-25 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SellerInfo',
            fields=[
                ('sellerID', models.BigAutoField(primary_key=True, serialize=False)),
                ('sellerName', models.CharField(max_length=255)),
                ('amazonID', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('nummer', models.IntegerField()),
                ('adresse', models.CharField(max_length=255)),
                ('productsType', models.CharField(max_length=255)),
                ('contacted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazonSeller.category')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amazonID', models.CharField(max_length=255)),
                ('sellerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazonSeller.sellerinfo')),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazonSeller.subcategory')),
            ],
        ),
    ]
