# Generated by Django 5.0.2 on 2024-02-11 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonSeller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='about_seller',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='asin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='main_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_category_products', to='amazonSeller.category'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='seller_detailed_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='seller_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='seller_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='store_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='sub_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_products', to='amazonSeller.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='amazonSeller.category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='link',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amazonSeller.country'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amazonSeller.country'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amazonSeller.country'),
        ),
        migrations.AlterUniqueTogether(
            name='productinfo',
            unique_together={('asin', 'country')},
        ),
    ]
