# Generated by Django 5.0 on 2023-12-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonSeller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
