# Generated by Django 5.0.2 on 2024-02-11 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonSeller', '0002_country_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazonSeller.country'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazonSeller.country'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazonSeller.country'),
        ),
    ]
