# Generated by Django 5.0.2 on 2024-02-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazonSeller', '0003_alter_category_country_alter_productinfo_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDE',
            fields=[
            ],
            options={
                'verbose_name': 'DE Category',
                'verbose_name_plural': 'DE Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('amazonSeller.category',),
        ),
        migrations.CreateModel(
            name='CategoryUS',
            fields=[
            ],
            options={
                'verbose_name': 'US Category',
                'verbose_name_plural': 'US Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('amazonSeller.category',),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'country')},
        ),
    ]
