# Generated by Django 5.0.2 on 2024-02-11 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonSeller', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazonSeller.country', to_field='code'),
        ),
    ]
