# Generated by Django 5.0.1 on 2024-02-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazonSeller', '0006_alter_productinfo_country'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productinfo',
            unique_together=set(),
        ),
    ]
