# Generated by Django 5.0.1 on 2024-02-12 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonSeller', '0007_alter_productinfo_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Us_productInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('store_name', models.CharField(max_length=255, null=True)),
                ('seller_name', models.CharField(max_length=255, null=True)),
                ('seller_id', models.CharField(max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('about_seller', models.TextField(null=True)),
                ('seller_detailed_info', models.TextField(null=True)),
                ('scraped', models.BooleanField(default=False)),
                ('contacted', models.BooleanField(default=False)),
                ('main_category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_category_products', to='amazonSeller.category')),
                ('sub_category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_products', to='amazonSeller.subcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductInfo',
        ),
    ]
