# Generated by Django 5.0.1 on 2024-02-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonSeller', '0009_alter_us_productinfo_main_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='de_productinfo',
            name='product_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='us_productinfo',
            name='product_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
